package registry

import "github.com/cruciblehq/crux/crex"

var (
	ErrNameEmpty           = crex.New("name cannot be empty")
	ErrNameTooLong         = crex.New("name cannot exceed 63 characters")
	ErrNameInvalid         = crex.New("invalid name")
	ErrVersionInvalid      = crex.New("version format must be semantic version")
	ErrTimestampInvalid    = crex.New("timestamp must be a positive unix epoch")
	ErrTimestampOrder      = crex.New("updatedAt must not be before createdAt")
	ErrTypeEmpty           = crex.New("resource type cannot be empty")
	ErrArchiveEmpty        = crex.New("archive URL cannot be empty when set")
	ErrSizeInvalid         = crex.New("archive size must be positive")
	ErrDigestInvalid       = crex.New("digest must be in algorithm:hex format")
	ErrArchiveIncomplete   = crex.New("archive, size, and digest must all be set or all be null")
	ErrCountNegative       = crex.New("count must not be negative")
	ErrErrorCodeInvalid    = crex.New("error code must be a known value")
	ErrErrorMessageEmpty   = crex.New("error message cannot be empty")
	ErrInvalidNamespace    = crex.New("invalid namespace")
	ErrInvalidResource     = crex.New("invalid resource")
	ErrInvalidVersion      = crex.New("invalid version")
	ErrInvalidChannel      = crex.New("invalid channel")
	ErrMarshal             = crex.New("failed to marshal request body")
	ErrBaseURL             = crex.New("failed to parse base URL")
	ErrHTTPRequest         = crex.New("failed to create HTTP request")
	ErrHTTPExecute         = crex.New("failed to execute HTTP request")
	ErrHTTPStatus          = crex.New("unexpected HTTP status")
	ErrResponseDecode      = crex.New("failed to decode response body")
	ErrTypeMismatch        = crex.New("resource type mismatch")
	ErrNoVersions          = crex.New("no versions found")
	ErrNoMatchingVersion   = crex.New("no matching version found")
	ErrMissingOption       = crex.New("missing required option")
	ErrMissingRegistry     = crex.New("default registry is required")
	ErrMissingNamespace    = crex.New("default namespace is required")
	ErrCacheOperation      = crex.New("cache operation failed")
	ErrFileSystemOperation = crex.New("file system operation failed")
	ErrNoArchive           = crex.New("version has no uploaded archive")
	ErrResolveVersion      = crex.New("failed to resolve version")
	ErrDownload            = crex.New("failed to download archive")
	ErrInvalidIdentifier   = crex.New("invalid resource identifier")
	ErrNamespaceNotFound   = crex.New("namespace not found")
	ErrVersionExists       = crex.New("version already exists")
	ErrRegistryOperation   = crex.New("registry operation failed")
)
