package reference

import "github.com/cruciblehq/crux/crex"

var (
	ErrInvalidIdentifier         = crex.New("invalid identifier")
	ErrInvalidReference          = crex.New("invalid reference")
	ErrInvalidVersion            = crex.New("invalid version")
	ErrInvalidDigest             = crex.New("invalid digest")
	ErrTypeMismatch              = crex.New("resource type mismatch")
	ErrInvalidContextType        = crex.New("invalid context type")
	ErrEmptyIdentifier           = crex.New("empty identifier")
	ErrInvalidRegistry           = crex.New("invalid registry")
	ErrInvalidPath               = crex.New("invalid path")
	ErrInvalidNamespace          = crex.New("invalid namespace")
	ErrInvalidName               = crex.New("invalid name")
	ErrEmptyReference            = crex.New("empty reference")
	ErrMissingVersionChannel     = crex.New("missing version or channel")
	ErrEmptyConstraint           = crex.New("empty constraint string")
	ErrEmptyConstraintGroup      = crex.New("empty constraint group")
	ErrBareWildcard              = crex.New("bare wildcard not allowed")
	ErrMultipleWildcards         = crex.New("multiple wildcards not allowed")
	ErrWildcardWithOperator      = crex.New("wildcard cannot have operator")
	ErrPrereleaseInConstraint    = crex.New("prerelease not allowed in constraint")
	ErrLeadingHyphen             = crex.New("leading hyphen in range")
	ErrTrailingHyphen            = crex.New("trailing hyphen in range")
	ErrConsecutiveHyphens        = crex.New("consecutive hyphens in range")
	ErrHyphenWithOperator        = crex.New("hyphen range with operator")
	ErrRangeBoundWithOperator    = crex.New("range bound cannot have operator")
	ErrRangeBoundWithWildcard    = crex.New("range bound cannot have wildcard")
	ErrMissingUpperBound         = crex.New("constraint requires explicit upper bound")
	ErrInvalidVersionFormat      = crex.New("invalid version format")
	ErrInvalidConstraintOperator = crex.New("invalid constraint operator")
	ErrInvalidRangeBound         = crex.New("invalid range bound")
	ErrEmptyOrExpression         = crex.New("empty version constraint in OR expression")
	ErrNilConstraint             = crex.New("cannot intersect nil constraints")
	ErrIncompatibleConstraints   = crex.New("constraints have no common versions")
	ErrUnexpectedToken           = crex.New("unexpected token")
	ErrInvalidBuildMetadata      = crex.New("invalid build metadata")
	ErrInvalidPrereleaseFormat   = crex.New("invalid prerelease format")
	ErrInvalidVersionComponents  = crex.New("version must have major.minor.patch")
	ErrInvalidMajorVersion       = crex.New("invalid major version")
	ErrInvalidMinorVersion       = crex.New("invalid minor version")
	ErrInvalidPatchVersion       = crex.New("invalid patch version")
	ErrMissingDigestColon        = crex.New("digest missing colon separator")
	ErrEmptyDigestAlgorithm      = crex.New("empty digest algorithm")
	ErrEmptyDigestHash           = crex.New("empty digest hash")
)
