package manifest

import "errors"

var (
	ErrInvalidResourceType     = errors.New("invalid resource type")
	ErrInvalidManifest         = errors.New("invalid manifest")
	ErrInvalidResource         = errors.New("invalid resource")
	ErrInvalidRecipe           = errors.New("invalid recipe")
	ErrInvalidStage            = errors.New("invalid stage")
	ErrInvalidStep             = errors.New("invalid step")
	ErrInvalidService          = errors.New("invalid service")
	ErrInvalidWidget           = errors.New("invalid widget")
	ErrUnsupportedVersion      = errors.New("unsupported manifest version")
	ErrMissingConfig           = errors.New("missing config")
	ErrConfigTypeMismatch      = errors.New("config type does not match resource type")
	ErrEncodeFailed            = errors.New("failed to encode manifest")
	ErrDecodeFailed            = errors.New("failed to decode manifest")
	ErrMissingName             = errors.New("missing resource name")
	ErrMissingVersion          = errors.New("missing resource version")
	ErrMissingOutputStage      = errors.New("recipe has no output stage")
	ErrDuplicateStageName      = errors.New("duplicate stage name")
	ErrNumericStageName        = errors.New("stage name must not be numeric")
	ErrMissingFrom             = errors.New("missing base image")
	ErrMutuallyExclusiveOps    = errors.New("run and copy are mutually exclusive")
	ErrEmptyStep               = errors.New("step has no fields set")
	ErrShellWithCopy           = errors.New("shell cannot be used with copy")
	ErrEnvWithCopy             = errors.New("env cannot be used with copy")
	ErrStepsWithoutPlatform    = errors.New("child steps require platform")
	ErrPlatformWithOperation   = errors.New("platform group cannot have operations")
	ErrNestedPlatformGroup     = errors.New("platform groups cannot be nested")
	ErrPlatformInPlatformStage = errors.New("steps cannot use platform inside a platform-scoped stage")
	ErrInvalidRef              = errors.New("invalid ref")
	ErrMissingRefTarget        = errors.New("missing ref target")
	ErrRefMixed                = errors.New("ref cannot have both a scalar value and args")
	ErrInvalidAffordance       = errors.New("invalid affordance")
	ErrInvalidGrant            = errors.New("invalid grant")
	ErrInvalidParam            = errors.New("invalid param")
	ErrMissingParamName        = errors.New("missing param name")
	ErrInvalidParamName        = errors.New("invalid param name")
	ErrInvalidParamDefault     = errors.New("invalid param default")
	ErrDuplicateParamName      = errors.New("duplicate param name")
	ErrDefaultNotInSchema      = errors.New("default param not in schema")
	ErrInvalidBlueprint        = errors.New("invalid blueprint")
	ErrMissingEntrypoint       = errors.New("service missing entrypoint")
	ErrMissingMain             = errors.New("widget missing main entry point")
	ErrMissingServiceID        = errors.New("service missing id")
	ErrDuplicateServiceID      = errors.New("duplicate service id")
	ErrMissingRoutePattern     = errors.New("route missing pattern")
	ErrMissingRouteService     = errors.New("route missing service")
	ErrRouteServiceNotFound    = errors.New("route references unknown service id")
	ErrDuplicateRoutePattern   = errors.New("duplicate route pattern")
	ErrMissingEnvironmentID    = errors.New("environment missing id")
	ErrDuplicateEnvironmentID  = errors.New("duplicate environment id")
	ErrInvalidPlan             = errors.New("invalid plan")
	ErrUnsupportedPlanVersion  = errors.New("unsupported plan version")
	ErrMissingComputeID        = errors.New("compute missing id")
	ErrMissingProvider         = errors.New("compute missing provider")
	ErrMissingContainerService = errors.New("container missing service")
	ErrMissingContainerCompute = errors.New("container missing compute")
	ErrInvalidState            = errors.New("invalid state")
	ErrUnsupportedStateVersion = errors.New("unsupported state version")
	ErrMissingDeployedAt       = errors.New("missing deployment timestamp")
)
